export const ActionType = {
  IS_LOGIN: 'IS_LOGIN',
  IS_LOADING: 'IS_LOADING',
  SET_EMPLOYEEHISTORY: 'EMPLOYEEHISTORY',
  SET_CERTIFICATION: 'SET_CERTIFICATION',
  SET_EXPERIENCE: 'SET_EXPERIENCE',
  SET_PORTFOLIO: 'SET_PORTFOLIO',
  SET_SETTINGS: 'SET_SETTINGS',
  SET_ACTIVATE_NAV: 'SET_ACTIVATE_NAV'
};
